#!/usr/bin/env bash

## https://gist.github.com/mark-akturatech/577e78ecfe33a5dd6386e46a4cfb833a

## Install ansible

#ansible-playbook local.yml --ask-become-pass --ask-vault-pass

# //0.0.0.0/MediaShare /mnt/scallion cifs uid=1000,rw,suid,credentials=/home/tom/.scallion_creds, 0 0
# username=XXX
# password=XXX


