- name: Install System Packages 1 (build-essential, cmake, pkg-config)
  become: true
  apt:
    name: ["build-essential", "cmake", "pkg-config"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 (unzip, libtool, libtool-bin, gettext)
  become: true
  apt:
    name: [ "unzip", "libtool", "libtool-bin", "gettext"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3 (the rest)
  become: true
  apt:
    name: [ "curl", "htop", "golang", "ninja-build", "g++", "autoconf", "automake", "doxygen" ]
  tags:
    - install
    - neovim
    - core

- name: gsettings keybindings
  shell: |
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-1 "['<Super>Home', '<Super>1']"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-2 "['<Super>2']"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-3 "['<Super>3']"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-4 "['<Super>4']"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-5 "['<Super>5']"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-6 "['<Super>6']"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-7 "['<Super>7']"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-8 "['<Super>8']"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-9 "['<Super>9']"
