- name: Install base-devel
  become: true
  community.general.pacman:
    name: ["base-devel", "cmake", "linux-firmware"]
    state: latest
  tags:
    - install
    - neovim
    - core

- name: Install System Packages
  become: true
  community.general.pacman:
    name: [ "lua51", "luarocks", "unzip", "alsa-utils", "clang", "openssh" ]
    state: latest
  tags:
    - install
    - neovim
    - core

# qt5-wayland: compat for keepassxc in wayland
- name: Install System Packages 2 (the rest)
  become: true
  community.general.pacman:
    name: [ "sway", "swaybg", "swayidle", "swaylock", "curl", "btop", "jq", "qt5-wayland", "pipewire", "pipewire-audio", "pipewire-pulse", "bluez", "bluez-utils", "bluez-deprecated-tools", "fwupd", "xdg-desktop-portal-wlr" ]
    state: latest
  tags:
    - install
    - core

- name: Install Fonts
  become: true
  community.general.pacman:
    name: [ "ttf-meslo-nerd", "noto-fonts", "noto-fonts-cjk", "noto-fonts-emoji", "noto-fonts-extra" ]
    state: latest
  tags:
    - install
    - core

- name: Terminal
  become: true
  community.general.pacman:
    name: [ "ghostty" ]
    state: latest
  tags:
    - install
    - core
