- name: Installing stow
  apt: name=stow
  become: true
  tags:
    - install
    - dotfiles
    - stow
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:tmlamb/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles
    - stow
- name: Remove existing zshrc
  shell: rm $HOME/.zshrc
  tags:
    - install
    - dotfiles
    - stow
- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./stowdirs
  tags:
    - install
    - dotfiles
    - stow
# Why does this command need to be run multiple times to 'take'? idk
- name: Bootstrap neovim packer plugins
  shell: |
    nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
    nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
    nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
  tags:
    - install
    - dotfiles
    - stow
    - neovim
