# See https://wiki.archlinux.org/title/Dropbox#Prevent_automatic_updates
- name: Remove .dropbox-dist
  become: true
  shell: "rm -rf {{ lookup('env', 'HOME') }}/.dropbox-dist"
  tags:
    - install
    - dropbox

- name: Create readonly .dropbox-dist
  shell: "install -dm0 {{ lookup('env', 'HOME') }}/.dropbox-dist"
  tags:
    - install
    - dropbox
