- name: Download kubectl binary
  shell: curl -L --output ~/.local/bin/kubectl "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
         && chmod +x ~/.local/bin/kubectl
  tags:
    - install
    - kubectl
