- name: Probable Pitchers exists
  stat:
    path: "{{ personal }}/probable-pitchers"
  register: probablepath
  tags:
    - install
    - personal-project
- name: Personal Project Probable Pitchers
  ansible.builtin.git:
    repo: 'git@github.com:tmlamb/probable-pitchers.git'
    accept_newhostkey: true
    bare: true
    dest: "{{ personal }}/probable-pitchers"
  tags:
    - install
    - personal-project
  when: probablepath.stat.exists == False
- name: Probable Pitchers Main Checkout
  shell: cd ~/personal/probable-pitchers && git fetch && git worktree add main main
  tags:
    - install
    - personal-project
  when: probablepath.stat.exists == False

- name: Activity Log Tracker exists
  stat:
    path: "{{ personal }}/activity-log-tracker"
  register: altpath
  tags:
    - install
    - personal-project
- name: Personal Activity Log Tracker
  ansible.builtin.git:
    repo: 'git@github.com:tmlamb/activity-log-tracker.git'
    accept_newhostkey: true
    bare: true
    dest: "{{ personal }}/activity-log-tracker"
  tags:
    - install
    - personal-project
  when: altpath.stat.exists == False
- name: Activity Log Tracker Main Checkout
  shell: cd ~/personal/activity-log-tracker && git fetch && git worktree add main main
  tags:
    - install
    - personal-project
  when: altpath.stat.exists == False
