- name: Probable Pitcher exists
  stat:
    path: "{{ personal }}/probable-pitcher/main"
  register: probablepath
  tags:
    - install
    - personal-project
- name: Personal Project Probable Pitcher
  ansible.builtin.git:
    repo: 'git@github.com:tmlamb/probable-pitcher.git'
    accept_newhostkey: true
    bare: true
    dest: "{{ personal }}/probable-pitcher/.bare"
  tags:
    - install
    - personal-project
  when: probablepath.stat.exists == False
- name: Probable Pitcher gitdir pointer
  shell: 'echo "gitdir: ./.bare" > {{ personal }}/probable-pitcher/.git'
  tags:
    - install
    - personal-project
  when: probablepath.stat.exists == False
- name: Probable Pitcher remote fetch config
  community.general.git_config:
    repo: "{{ personal }}/probable-pitcher/.bare"
    scope: local
    name: remote.origin.fetch
    value: '+refs/heads/*:refs/remotes/origin/*'
  tags:
    - install
    - personal-project
  when: probablepath.stat.exists == False
- name: Probable Pitcher Main Checkout
  shell: cd ~/personal/probable-pitcher && git fetch && git worktree add main main
  tags:
    - install
    - personal-project
  when: probablepath.stat.exists == False

- name: Activity Log Tracker exists
  stat:
    path: "{{ personal }}/activity-log-tracker/main"
  register: altpath
  tags:
    - install
    - personal-project
- name: Personal Activity Log Tracker
  ansible.builtin.git:
    repo: 'git@github.com:tmlamb/activity-log-tracker.git'
    accept_newhostkey: true
    bare: true
    dest: "{{ personal }}/activity-log-tracker/.bare"
  tags:
    - install
    - personal-project
  when: altpath.stat.exists == False
- name: Activity Log Tracker gitdir pointer
  shell: 'echo "gitdir: ./.bare" > {{ personal }}/activity-log-tracker/.git'
  tags:
    - install
    - personal-project
  when: altpath.stat.exists == False
- name: Activity Log Tracker remote fetch config
  community.general.git_config:
    repo: "{{ personal }}/activity-log-tracker/.bare"
    scope: local
    name: remote.origin.fetch
    value: '+refs/heads/*:refs/remotes/origin/*'
  tags:
    - install
    - personal-project
  when: altpath.stat.exists == False
- name: Activity Log Tracker Main Checkout
  shell: cd ~/personal/activity-log-tracker && git fetch && git worktree add main main
  tags:
    - install
    - personal-project
  when: altpath.stat.exists == False
