- name: Install packages
  become: true
  community.general.pacman:
    name: [ "tmux", "fzf", "gimp", "tldr", "ripgrep", "keepassxc", "fd", "brightnessctl", "grim", "imv", "firefox", "pulumi", "playerctl", "wl-clipboard", "swayimg", "yt-dlp" ]
    state: latest
  tags:
    - install
    - productivity

- name: Ensure screenshot directory exists.
  file:
    path: "{{ lookup('env', 'HOME') }}/screenshots"
    state: directory
  tags:
    - install
    - fonts
