- name: Install packages
  become: true
  apt:
    name: [ "tmux", "wireshark", "fzf", "gimp", "xclip", "screenkey", "tldr", "ripgrep", "keepassxc", "openscad", "wireguard" ]
  tags:
    - install
    - productivity
