- name: Remove yay
  ansible.builtin.file:
    state: absent
    path: "/tmp/yay/"
  tags:
    - install
    - yay

- name: Clone yay AUR
  ansible.builtin.git:
    repo: "https://aur.archlinux.org/yay.git"
    dest: "/tmp/yay"
    update: true
  tags:
    - install
    - dropbox

- name: Install yay
  shell: "cd /tmp/yay && makepkg -si --noconfirm"
  tags:
    - install
    - dropbox
