- name: Remove yay
  ansible.builtin.file:
    state: absent
    path: "/tmp/yay/"
  tags:
    - install
    - yay

- name: Clone yay AUR
  ansible.builtin.git:
    repo: "https://aur.archlinux.org/yay.git"
    dest: "/tmp/yay"
    update: true
  tags:
    - install
    - yay

- name: Build yay artifact
  ansible.builtin.command: "makepkg -cf --noconfirm"
  args:
    chdir: "/tmp/yay"
  become: false # Run as user, no sudo needed purely for building
  tags:
    - install
    - yay

- name: Find built package
  ansible.builtin.find:
    paths: "/tmp/yay"
    patterns: "yay-*.pkg.tar.zst"
  register: yay_package_file
  tags:
    - install
    - yay

- name: Install yay locally
  community.general.pacman:
    name: "{{ yay_package_file.files[0].path }}"
    state: present
  become: true # Ansible handles the sudo password here
  tags:
    - install
    - yay

# - name: Install yay
#   shell: "cd /tmp/yay && makepkg -si --noconfirm"
#   tags:
#     - install
#     - yay
